[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/imgbb-upload"
  status = 200

[[headers]]
  for = "/api/upload-image"
  [headers.values]
    Cache-Control = "no-store"
